/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.OrderController;
import java.awt.Color;
import javax.swing.JOptionPane;
import model.Order;
import util.RoundedButton;
import util.RoundedJTextFiled;
import util.RoundedJComboBox;

/**
 *
 * @author Sachintha
 */
public class UpdateOrderForm extends javax.swing.JFrame {

    private OrderController orderController;
    private Order order;

    /**
     * Creates new form PlaceOrderForm
     *
     * @param orderController
     */
    public UpdateOrderForm(OrderController orderController) {
        initComponents();
        setLocationRelativeTo(null);
        this.orderController = orderController;

        RoundedButton.makeButtonRounded(btnUpdateOrder, 40, new Color(1, 177, 59), Color.WHITE);
        RoundedButton.makeButtonRounded(btnBack, 40, new Color(208, 73, 70), Color.WHITE);
        RoundedJTextFiled.makeTextFieldRounded(txtCustomerId, 15, Color.LIGHT_GRAY, Color.GRAY);
        RoundedJTextFiled.makeTextFieldRounded(txtQty, 15, Color.WHITE, Color.GRAY);
        RoundedJTextFiled.makeTextFieldRounded(txtOrderId, 15, Color.WHITE, Color.GRAY);
        RoundedJTextFiled.makeTextFieldRounded(txtName, 15, Color.LIGHT_GRAY, Color.GRAY);
        RoundedJComboBox.makeComboBoxRounded(cmbStatus, 15, new Color(238, 238, 238), new Color(180, 180, 180));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        lblCustomerId = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblStatus = new javax.swing.JLabel();
        txtTotal = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnUpdateOrder = new javax.swing.JButton();
        cmbStatus = new javax.swing.JComboBox<>();
        txtOrderId = new javax.swing.JTextField();
        lblCustomerId1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        lblError1 = new javax.swing.JLabel();
        lblError2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jPanel1.setBackground(new java.awt.Color(208, 72, 74));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Order");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        lblOrderId.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblOrderId.setText("Order Id  ");

        lblCustomerId.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCustomerId.setText("Customer Id ");

        txtCustomerId.setEditable(false);
        txtCustomerId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblQty.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblQty.setText("Order QTY ");

        txtQty.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQtyActionPerformed(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtQtyKeyReleased(evt);
            }
        });

        lblStatus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblStatus.setText("Order Status  ");

        txtTotal.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtTotal.setForeground(new java.awt.Color(208, 73, 70));

        btnBack.setBackground(new java.awt.Color(208, 73, 70));
        btnBack.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdateOrder.setBackground(new java.awt.Color(1, 177, 59));
        btnUpdateOrder.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnUpdateOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateOrder.setText("Update Order");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select an Option", "Pending", "Delivered", "Cancelled" }));

        txtOrderId.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtOrderId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrderIdKeyReleased(evt);
            }
        });

        lblCustomerId1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblCustomerId1.setText("Name");

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        lblTotal.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTotal.setText("Total");

        lblError1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblError1.setForeground(new java.awt.Color(208, 73, 70));

        lblError2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblError2.setForeground(new java.awt.Color(208, 73, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCustomerId)
                        .addGap(28, 28, 28)
                        .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblCustomerId1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQty)
                            .addComponent(lblTotal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblError1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblError2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(230, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateOrder)
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblError1)
                        .addGap(2, 2, 2)
                        .addComponent(lblError2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(lblCustomerId1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQty, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }// GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateOrderActionPerformed
        if (order != null) {
            int newQty = Integer.parseInt(txtQty.getText());
            String newStatus = (String) cmbStatus.getSelectedItem();

            boolean isQtyChanged = order.getQuantity() != newQty;
            boolean isStatusChanged = !newStatus.equals(order.getStatus());

            if (isQtyChanged || isStatusChanged) {
                if (isQtyChanged) {
                    order.setQuantity(newQty);
                    order.setAmount(order.getQuantity() * Order.BURGERPRICE);
                }

                if (isStatusChanged) {
                    order.setStatus(newStatus);
                }

                if (orderController.updateOrder(order)) {
                    JOptionPane.showMessageDialog(this, "Order Successfully Updated..!");
                } else {
                    JOptionPane.showMessageDialog(this, "Something went wrong. Order Not Updated..!");
                }

                resetForm(true);
            } else {
                JOptionPane.showMessageDialog(this, "Nothing Updated. Please update the Quantity or Status and try again...");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter the Order ID first...");
        }
    }// GEN-LAST:event_btnUpdateOrderActionPerformed

    private void txtQtyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtQtyActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtQtyActionPerformed

    private void txtQtyKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtQtyKeyReleased
        try {
            int qty = Integer.parseInt(txtQty.getText());
            double total = qty * Order.BURGERPRICE;
            txtTotal.setText(String.format("%.2f", total));
        } catch (NumberFormatException e) {
            txtTotal.setText("0.00");
        }
    }// GEN-LAST:event_txtQtyKeyReleased

    private void txtOrderIdKeyReleased(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_txtOrderIdKeyReleased

        cmbStatus.enable();

        String orderId = txtOrderId.getText();

        order = orderController.searchOrder(orderId);

        if (order != null) {
            int index = 0;
            String errorStatus = "";
            switch (order.getStatus()) {
                case "Pending":
                    index = 1;
                    break;
                case "Delivered":
                    index = 2;
                    errorStatus = "Delivered";
                    break;
                case "Cancelled":
                    index = 3;
                    errorStatus = "Cancelled";
                    break;
            }

            if (index == 2 || index == 3) {
                cmbStatus.disable();
                txtQty.setEditable(false);
                lblError1.setText("The order has been " + errorStatus);
                lblError2.setText("Sorry..you can not update this order");
            }

            cmbStatus.setSelectedIndex(index);
            txtCustomerId.setText(order.getCustomerId());
            txtName.setText(order.getCustomerName());
            txtQty.setText(String.valueOf(order.getQuantity()));
            txtTotal.setText(String.format("%.2f", order.getAmount()));
        } else {
            resetForm(false);
        }
    }// GEN-LAST:event_txtOrderIdKeyReleased

    private void resetForm(boolean orderIdInclude) {

        cmbStatus.setSelectedIndex(0);
        txtCustomerId.setText("");
        txtName.setText("");
        txtQty.setText("");
        txtTotal.setText("");
        lblError1.setText("");
        lblError2.setText("");

        if (orderIdInclude) {
            txtOrderId.setText("");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblCustomerId1;
    private javax.swing.JLabel lblError1;
    private javax.swing.JLabel lblError2;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtQty;
    private javax.swing.JLabel txtTotal;
    // End of variables declaration//GEN-END:variables
}
