/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.OrderController;
import javax.swing.*;
import java.awt.*;
import util.RoundedButton;

/**
 *
 * @author Sachintha
 */
public class ViewOrdersForm extends javax.swing.JFrame {

    private OrderController orderController;
    private DeliveredOrdersForm deliveredOrdersForm;
    private ProcessingOrdersForm processingOrdersForm;

    /**
     * Creates new form HomePageForm
     *
     * @param orderController
     */
    public ViewOrdersForm(OrderController orderController) {
        initComponents();
        setLocationRelativeTo(null);
        this.orderController = orderController;

        setScaledImageToLabel(lblLogo, "/images/logo.png");

        lblLogo.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                setScaledImageToLabel(lblLogo, "/images/logo.png");
            }
        });

        RoundedButton.makeButtonRounded(btnDeliveredOrders, 40, new Color(208, 73, 70), Color.WHITE);
        RoundedButton.makeButtonRounded(btnProcessingOrders, 40, new Color(208, 73, 70), Color.WHITE);
        RoundedButton.makeButtonRounded(btnCanceledOrders, 40, new Color(208, 73, 70), Color.WHITE);
        RoundedButton.makeButtonRounded(btnExit, 35, new Color(208, 73, 70), Color.WHITE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogo = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnDeliveredOrders = new javax.swing.JButton();
        btnProcessingOrders = new javax.swing.JButton();
        btnCanceledOrders = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(560, 290));
        setPreferredSize(new java.awt.Dimension(850, 545));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        btnDeliveredOrders.setBackground(new java.awt.Color(208, 73, 70));
        btnDeliveredOrders.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnDeliveredOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveredOrders.setText("Delivered Orders");
        btnDeliveredOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeliveredOrdersActionPerformed(evt);
            }
        });

        btnProcessingOrders.setBackground(new java.awt.Color(208, 73, 70));
        btnProcessingOrders.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnProcessingOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnProcessingOrders.setText("Processing Orders");
        btnProcessingOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessingOrdersActionPerformed(evt);
            }
        });

        btnCanceledOrders.setBackground(new java.awt.Color(208, 73, 70));
        btnCanceledOrders.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnCanceledOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnCanceledOrders.setText("Canceled Orders");
        btnCanceledOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanceledOrdersActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(208, 73, 70));
        btnExit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(208, 73, 70));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View Orders");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeliveredOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProcessingOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCanceledOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))))
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(btnDeliveredOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnProcessingOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnCanceledOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        lblTitle.setFont(new java.awt.Font("Calibri", 1, 30)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(191, 169, 67));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Welcome to Burgers");
        lblTitle.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)))
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeliveredOrdersActionPerformed(java.awt.event.ActionEvent evt) {
        if (deliveredOrdersForm == null || !deliveredOrdersForm.isDisplayable()) {
            deliveredOrdersForm = new DeliveredOrdersForm(orderController);
            deliveredOrdersForm.setVisible(true);
        } else {
            deliveredOrdersForm.toFront();
        }
    }

    private void btnProcessingOrdersActionPerformed(java.awt.event.ActionEvent evt) {
        if (processingOrdersForm == null || !processingOrdersForm.isDisplayable()) {
            processingOrdersForm = new ProcessingOrdersForm(orderController);
            processingOrdersForm.setVisible(true);
        } else {
            processingOrdersForm.toFront();
        }
    }

    private void btnCanceledOrdersActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnExitActionPerformed
        dispose();
    }// GEN-LAST:event_btnExitActionPerformed

    private void setScaledImageToLabel(JLabel label, String resourcePath) {
        java.net.URL imgUrl = getClass().getResource(resourcePath);
        if (imgUrl == null) {
            return;
        }

        ImageIcon icon = new ImageIcon(imgUrl);
        int w = label.getWidth();
        int h = label.getHeight();
        if (w <= 0 || h <= 0) {
            return;
        }

        Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        label.setIcon(new ImageIcon(img));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanceledOrders;
    private javax.swing.JButton btnDeliveredOrders;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnProcessingOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables
}
